package io.github.therealkamisama.miguelnetwork.server;

import io.github.therealkamisama.miguelnetwork.config.DeploymentMode;

import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.OptionalInt;
import java.util.Properties;

final class ServerEndpointResolver {
    private ServerEndpointResolver() {
    }

    static ResolvedEndpoints resolve(Path gameDirectory, int runningMinecraftPort, OptionalInt zstdNetPort)
            throws IOException {
        Properties properties = new Properties();
        Path serverProperties = gameDirectory.resolve("server.properties");
        if (Files.isRegularFile(serverProperties)) {
            try (Reader reader = Files.newBufferedReader(serverProperties, StandardCharsets.UTF_8)) {
                properties.load(reader);
            }
        }
        String configuredIp = properties.getProperty("server-ip", "").trim();
        String targetHost = targetHost(configuredIp);
        return new ResolvedEndpoints(configuredIp, targetHost, runningMinecraftPort,
                zstdNetPort.isPresent() ? zstdNetPort.getAsInt() : null);
    }

    static void writeDetectedConfiguration(
            Path gameDirectory,
            ResolvedEndpoints endpoints,
            DeploymentMode mode,
            String publicBindHost,
            int publicPort
    ) throws IOException {
        Path output = gameDirectory.resolve("config/miguelnetwork/generated/detected-server.toml");
        Files.createDirectories(output.getParent());
        String zstdPort = endpoints.zstdNetPort() == null ? "0" : endpoints.zstdNetPort().toString();
        String content = "# Generated by MiguelNetwork. Do not edit; change server.properties, ZstdNet, or "
                + "miguelnetwork-server.toml instead.\n"
                + "deploymentMode = \"" + mode + "\"\n"
                + "publicBindHost = \"" + escape(publicBindHost) + "\"\n"
                + "publicPort = " + publicPort + "\n"
                + "serverPropertiesIp = \"" + escape(endpoints.configuredServerIp()) + "\"\n"
                + "minecraftTargetHost = \"" + escape(endpoints.targetHost()) + "\"\n"
                + "minecraftTargetPort = " + endpoints.minecraftPort() + "\n"
                + "zstdNetDetected = " + (endpoints.zstdNetPort() != null) + "\n"
                + "zstdNetTargetHost = \"" + escape(endpoints.targetHost()) + "\"\n"
                + "zstdNetTargetPort = " + zstdPort + "\n";
        Files.writeString(output, content, StandardCharsets.UTF_8);
    }

    private static String targetHost(String configuredIp) {
        if (configuredIp.isBlank() || configuredIp.equals("0.0.0.0") || configuredIp.equals("::")
                || configuredIp.equals("[::]")) {
            return "127.0.0.1";
        }
        return configuredIp.startsWith("[") && configuredIp.endsWith("]")
                ? configuredIp.substring(1, configuredIp.length() - 1) : configuredIp;
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    record ResolvedEndpoints(
            String configuredServerIp,
            String targetHost,
            int minecraftPort,
            Integer zstdNetPort
    ) {
    }
}
